# example netlify.toml
[build]
  command = "yarn run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/qrz-proxy/*"
  to = "https://logbook.qrz.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger.org/*"
  to = "http://netlogger.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger.org/*"
  to = "http://www.netlogger.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger1.org/*"
  to = "http://netlogger1.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger1.org/*"
  to = "http://www.netlogger1.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger2.org/*"
  to = "http://netlogger2.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger2.org/*"
  to = "http://www.netlogger2.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger3.org/*"
  to = "http://netlogger3.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger3.org/*"
  to = "http://www.netlogger3.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger4.org/*"
  to = "http://netlogger4.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger4.org/*"
  to = "http://www.netlogger4.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger5.org/*"
  to = "http://netlogger5.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger5.org/*"
  to = "http://www.netlogger5.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/netlogger6.org/*"
  to = "http://netlogger6.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlogger-proxy/www.netlogger6.org/*"
  to = "http://www.netlogger6.org/:splat"
  status = 200
  force = true

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection

[dev]
  port = 3004 # Port that the dev server will be listening on
  targetPort = 3003
  # command = "yarn start" # Command to start your dev server
  # publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
