# example netlify.toml
[build]
  command = "yarn run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/cors-proxy/*"
  to = ":splat"
  status = 200
  force = true

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection

[dev]
  port = 3004 # Port that the dev server will be listening on
  targetPort = 3003
  # command = "yarn start" # Command to start your dev server
  # publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
